### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Horhik/Instagram2Fedi#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by Horhik** [comment]
Oh, forgot to use my lovely GPLv3

**Comment by Horhik** [comment]
Fixed in 279dbf2e2412a8b307d13d34447ae8ff9a36302b
