### ISSUE TITLE
instagram feed doesn't exist?

### ISSUE THREAD

**Issue by honorash** [Horhik/Instagram2Fedi#10]
i had been using this just fine but on running today i was faced with a couple of fun errors
- instaloader.exceptions.ProfileNotExistsException: Profile _username_ does not exist.
and then on retrying 
- instaloader.exceptions.ConnectionException: JSON Query to _username_/feed/: Could not find "window._sharedData" in html response.

is this a me issue or an ig issue? sorry, not too hot on python so limited capacity to troubleshoot myself.

**Comment by Horhik** [comment]
As I understood there's problem with instagram itself, because since "i don't know when" it's not possible to acces to any profile if you're not logged in. 

Because of that my script is crashing.

**Comment by Horhik** [comment]
I thin i fixed it in [this release](https://github.com/Horhik/Instagram2Fedi/releases/tag/v0.3.1l) v0.3.1
Now authorization is required
