### ISSUE TITLE
How to get the token

### ISSUE THREAD

**Issue by tzugen** [Horhik/Instagram2Fedi#20]
Please provide some docs how and where to generate the access token...

**Comment by tzugen** [comment]
https://takahashim.github.io/mastodon-access-token/

**Comment by jsailo** [comment]
@tzugen Which of the following did you use? 1 or 2?

![image](https://github.com/Horhik/Instagram2Fedi/assets/35369823/7da4e860-139e-48a2-9690-352809fbdca5)

**Comment by tzugen** [comment]
Hi sorry.. I think I took the first.. Which is empty for you?

**Comment by tzugen** [comment]
But never got it working. The log complained that I need to login with Insta, even though I passed the detaiks

**Comment by jsailo** [comment]
Oh. It should not be empty? What should I fill up in the `Client Name`? I left it as sample-client. I'm using Pleroma with Soapbox as the FE BTW.

I dilly dallied around with options 1 and 2 but got the following. It didn't work, of course :)

https://www.instagram.com/challenge/AXEJIAsYDEghZzyOmTCMR6khHrQZbcMmcafvXnhY9bAkATFiq_pwQLRI7szWgwK2Zh-3/AfzGaEafPqGz9z4rwlEosLRVINhfNHeN7D8EIq77ERZxS72yS4F20aV-0Isj8mudlc2rktwqaGQq2A/?challenge_context=long_list_of_random_characters

**Comment by Horhik** [comment]
> Please provide some docs how and where to generate the access token...

There's just a "Development" section in settings of your mastodon account, and same for pixelfed too
