### ISSUE TITLE
requipments.txt ?

### ISSUE THREAD

**Issue by ManuLinares** [Horhik/Instagram2Fedi#4]
https://github.com/Horhik/Instagram2Fedi/blob/main/src/requipments.txt

**Comment by Horhik** [comment]
Oh... didn't notice what I created two requipments.txt.

Now I just put one in the root folder
https://github.com/Horhik/Instagram2Fedi/blob/main/requirements.txt

**Comment by ManuLinares** [comment]
It was the typo that bothered me 😊
